// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnityDataImporter.Data;

#nullable disable

namespace UnityDataImporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnityDataImporter.Models.EffectType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("EffectType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.EquipmentSlotType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("EquipmentSlotType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.EventType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("eventName");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea")
                        .HasColumnName("icon");

                    b.HasKey("Id");

                    b.ToTable("eventType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.HoldType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("HoldType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.InventorySound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sound");

                    b.HasKey("Id");

                    b.ToTable("InventorySound", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<float?>("BlockAmount")
                        .HasColumnType("real")
                        .HasColumnName("blockAmount");

                    b.Property<long?>("BlockSounds")
                        .HasColumnType("bigint")
                        .HasColumnName("blockSounds");

                    b.Property<int?>("BuyAmount")
                        .HasColumnType("integer")
                        .HasColumnName("buyAmount");

                    b.Property<bool?>("CanBlock")
                        .HasColumnType("boolean")
                        .HasColumnName("canBlock");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EquipmentSlot")
                        .HasColumnType("text")
                        .HasColumnName("equipmentSlot");

                    b.Property<string>("HoldType")
                        .HasColumnType("text")
                        .HasColumnName("holdType");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea")
                        .HasColumnName("icon");

                    b.Property<bool?>("IsStackable")
                        .HasColumnType("boolean")
                        .HasColumnName("isStackable");

                    b.Property<string>("ItemAnimations")
                        .HasColumnType("jsonb")
                        .HasColumnName("itemAnimations");

                    b.Property<string>("ItemEvents")
                        .HasColumnType("jsonb")
                        .HasColumnName("itemEvents");

                    b.Property<string>("ItemRarity")
                        .HasColumnType("text")
                        .HasColumnName("itemRarity");

                    b.Property<long?>("ItemSize")
                        .HasColumnType("bigint")
                        .HasColumnName("itemSize");

                    b.Property<long?>("ItemSoundType")
                        .HasColumnType("bigint")
                        .HasColumnName("itemSoundType");

                    b.Property<string>("ItemStats")
                        .HasColumnType("jsonb")
                        .HasColumnName("itemStats");

                    b.Property<string>("ItemType")
                        .HasColumnType("text")
                        .HasColumnName("itemType");

                    b.Property<int?>("MaxAmount")
                        .HasColumnType("integer")
                        .HasColumnName("maxAmount");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParryAudio")
                        .HasColumnType("bigint")
                        .HasColumnName("parryAudio");

                    b.Property<int?>("SellAmount")
                        .HasColumnType("integer")
                        .HasColumnName("sellAmount");

                    b.HasKey("Id");

                    b.HasIndex("BlockSounds");

                    b.HasIndex("EquipmentSlot");

                    b.HasIndex("HoldType");

                    b.HasIndex("ItemRarity");

                    b.HasIndex("ItemSize");

                    b.HasIndex("ItemSoundType");

                    b.HasIndex("ItemType");

                    b.HasIndex("ParryAudio");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.ItemAudio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Audio")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("audio");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.HasKey("Id");

                    b.ToTable("itemAudio", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.ItemEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventTypeId")
                        .HasColumnType("text")
                        .HasColumnName("eventTypeId");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemId");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("ItemId");

                    b.ToTable("itemEvent", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.ItemType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("ItemType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.LootTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LootTableDatas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lootTableDatas");

                    b.Property<string>("LootTableId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lootTableId");

                    b.Property<string>("LootTableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lootTableName");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId")
                        .IsUnique();

                    b.ToTable("LootTables", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.LootTableData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemId");

                    b.Property<string>("LootTableId")
                        .HasColumnType("text")
                        .HasColumnName("lootTableId");

                    b.Property<int?>("MaxAmount")
                        .HasColumnType("integer")
                        .HasColumnName("maxAmount");

                    b.Property<int?>("MinAmount")
                        .HasColumnType("integer")
                        .HasColumnName("minAmount");

                    b.Property<int?>("Probability")
                        .HasColumnType("integer")
                        .HasColumnName("probability");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LootTableId");

                    b.ToTable("lootTableData", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.MagicAttack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float?>("Cooldown")
                        .HasColumnType("real")
                        .HasColumnName("cooldown");

                    b.Property<string>("EffectType")
                        .HasColumnType("text")
                        .HasColumnName("effectType");

                    b.Property<string>("HitSounds")
                        .HasColumnType("jsonb")
                        .HasColumnName("hitSounds");

                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasColumnName("itemId");

                    b.Property<int?>("MagicDamage")
                        .HasColumnType("integer")
                        .HasColumnName("magicDamage");

                    b.Property<string>("MagicType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("magicType");

                    b.Property<int?>("ManaConsumption")
                        .HasColumnType("integer")
                        .HasColumnName("manaConsumption");

                    b.Property<int?>("MaxCompanions")
                        .HasColumnType("integer")
                        .HasColumnName("maxCompanions");

                    b.Property<float?>("ProjectileSpeed")
                        .HasColumnType("real")
                        .HasColumnName("projectileSpeed");

                    b.HasKey("Id");

                    b.HasIndex("EffectType");

                    b.HasIndex("ItemId");

                    b.HasIndex("MagicType");

                    b.ToTable("magicAttacks", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.MagicStatusEffect", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("magicStatusEffect", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.MagicType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("magicType", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.NpcShop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LootTableId")
                        .HasColumnType("text")
                        .HasColumnName("lootTableId");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Recipes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recipes");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("NpcsShop", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Rarity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("Rarity", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("InputItems")
                        .HasColumnType("json")
                        .HasColumnName("inputItems");

                    b.Property<string>("OutputItems")
                        .HasColumnType("json")
                        .HasColumnName("outputItems");

                    b.Property<int?>("RecipeCost")
                        .HasColumnType("integer")
                        .HasColumnName("recipeCost");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipeName");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.SoundsArray", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemId");

                    b.Property<string>("Sounds")
                        .HasColumnType("json")
                        .HasColumnName("sounds");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SoundsArray", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Stats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("Stats", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.StatsAmount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Item")
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.HasKey("Id");

                    b.HasIndex("Item");

                    b.HasIndex("Stat");

                    b.ToTable("Stats_Amount", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Vector2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.ToTable("Vector2", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.WeaponData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ammo")
                        .HasColumnType("text")
                        .HasColumnName("ammo");

                    b.Property<float?>("Cooldown")
                        .HasColumnType("real")
                        .HasColumnName("cooldown");

                    b.Property<long?>("Damage")
                        .HasColumnType("bigint")
                        .HasColumnName("damage");

                    b.Property<float?>("Heaviness")
                        .HasColumnType("real")
                        .HasColumnName("heaviness");

                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasColumnName("itemId");

                    b.HasKey("Id");

                    b.HasIndex("Ammo");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("WeaponData", (string)null);
                });

            modelBuilder.Entity("UnityDataImporter.Models.Item", b =>
                {
                    b.HasOne("UnityDataImporter.Models.ItemAudio", "BlockSoundsNavigation")
                        .WithMany()
                        .HasForeignKey("BlockSounds");

                    b.HasOne("UnityDataImporter.Models.EquipmentSlotType", "EquipmentSlotNavigation")
                        .WithMany()
                        .HasForeignKey("EquipmentSlot");

                    b.HasOne("UnityDataImporter.Models.HoldType", "HoldTypeNavigation")
                        .WithMany()
                        .HasForeignKey("HoldType");

                    b.HasOne("UnityDataImporter.Models.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("ItemRarity");

                    b.HasOne("UnityDataImporter.Models.Vector2", "Size")
                        .WithMany()
                        .HasForeignKey("ItemSize");

                    b.HasOne("UnityDataImporter.Models.InventorySound", "SoundType")
                        .WithMany()
                        .HasForeignKey("ItemSoundType");

                    b.HasOne("UnityDataImporter.Models.ItemType", "Type")
                        .WithMany()
                        .HasForeignKey("ItemType");

                    b.HasOne("UnityDataImporter.Models.ItemAudio", "ParryAudioNavigation")
                        .WithMany()
                        .HasForeignKey("ParryAudio");

                    b.Navigation("BlockSoundsNavigation");

                    b.Navigation("EquipmentSlotNavigation");

                    b.Navigation("HoldTypeNavigation");

                    b.Navigation("ParryAudioNavigation");

                    b.Navigation("Rarity");

                    b.Navigation("Size");

                    b.Navigation("SoundType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("UnityDataImporter.Models.ItemEvent", b =>
                {
                    b.HasOne("UnityDataImporter.Models.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId");

                    b.HasOne("UnityDataImporter.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UnityDataImporter.Models.LootTableData", b =>
                {
                    b.HasOne("UnityDataImporter.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnityDataImporter.Models.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .HasPrincipalKey("LootTableId");

                    b.Navigation("Item");

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("UnityDataImporter.Models.MagicAttack", b =>
                {
                    b.HasOne("UnityDataImporter.Models.EffectType", "EffectTypeNavigation")
                        .WithMany()
                        .HasForeignKey("EffectType");

                    b.HasOne("UnityDataImporter.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("UnityDataImporter.Models.MagicType", "MagicTypeNavigation")
                        .WithMany()
                        .HasForeignKey("MagicType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffectTypeNavigation");

                    b.Navigation("Item");

                    b.Navigation("MagicTypeNavigation");
                });

            modelBuilder.Entity("UnityDataImporter.Models.NpcShop", b =>
                {
                    b.HasOne("UnityDataImporter.Models.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .HasPrincipalKey("LootTableId");

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("UnityDataImporter.Models.SoundsArray", b =>
                {
                    b.HasOne("UnityDataImporter.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UnityDataImporter.Models.StatsAmount", b =>
                {
                    b.HasOne("UnityDataImporter.Models.Item", "ItemNavigation")
                        .WithMany()
                        .HasForeignKey("Item");

                    b.HasOne("UnityDataImporter.Models.Stats", "StatNavigation")
                        .WithMany()
                        .HasForeignKey("Stat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemNavigation");

                    b.Navigation("StatNavigation");
                });

            modelBuilder.Entity("UnityDataImporter.Models.WeaponData", b =>
                {
                    b.HasOne("UnityDataImporter.Models.Item", "AmmoItem")
                        .WithMany()
                        .HasForeignKey("Ammo");

                    b.HasOne("UnityDataImporter.Models.Item", "Item")
                        .WithOne("Weapon")
                        .HasForeignKey("UnityDataImporter.Models.WeaponData", "ItemId");

                    b.Navigation("AmmoItem");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UnityDataImporter.Models.Item", b =>
                {
                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("UnityDataImporter.Models.LootTable", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
